version: '3'
services:  
  app:
    build: ./api/src
    ports:
      - 8080
    environment:
      - GIN_MODE=release
  
  nginx:
    image: nginx:1.15.2
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app