version: '3'
services:  
  api:
    build: ./api/src
    ports:
      - 8080
    environment:
      # - GIN_MODE=release
      - DB_CONN_STR=postgres:@localhost:5432/dev
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api

  db:
    build: ./db
    ports:
      - 5432:5432