version: '3'
services:  
  api:
    build: ./api/src
    ports:
      - 8080
    environment:
      - GIN_MODE=release
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api